sudo: required

services:
  - docker

before_install:
  - docker build -t 1fckdup/react-ci-demo -f Dockerfile.dev .


script:
  - docker run -e CI=true 1fckdup/react-ci-demo npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-ci-demo"
  env: "DockerCiDemo-env"
  bucket_name: "elasticbeanstalk-us-east-2-343414328419"
  bucket_path: "docker-ci-demo"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
